### ISSUE TITLE
As a player (user/guest) I want to join a game by entering a game code to play with others

### ISSUE THREAD

**Issue by RoVi80** [sopra-fs23-group-08/client#36]
Story : As a player, I want to be able to join a game by typing in the game code to play with other users  

Acceptance criteria: 

- [x] sopra-fs23-group-08/client#9
- [x] sopra-fs23-group-08/client#10

Priority: Critical 
Estimate: 4-8 h

**Comment by Dedphish** [comment]
For linked commits see sub-tasks
